<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to suporte@tray.net.br so we can send you a copy immediately.
 *
 * @category   Tray
 * @package    Tray_CheckoutRedir
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="page-head">
    <h2 class="sub-title">Erro ao realizar o Retorno Autom&aacute;tico</h2>
</div>
<table style="width:100%;">
    <tr>
        <td style="width:100%">
            Ocorreu um erro ao realizar o retorno autom&aacute;tico.<br /><br />
            Dados do Erro:<br />
            C&oacute;digo: <?php echo utf8_decode($this->getRequest()->getParam("codigo"));  ?><br />
            Descri&ccedil;&atilde;o: <?php echo utf8_decode($this->getRequest()->getParam("descricao"));  ?><br />
        </td>
    </tr>
</table>