<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to suporte@tray.net.br so we can send you a copy immediately.
 *
 * @category   Tray
 * @package    Tray_CheckoutRedir
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<fieldset class="form-list">
    <?php 
          $_code = $this->getMethodCode();
          $_standardPD = Mage::getSingleton('checkoutredir/geral');
          
          $totals = Mage::getSingleton('checkout/session')->getQuote()->collectTotals();  
          //$shippingAmount = Mage::getSingleton('checkout/session')->getQuote()->getShippingAddress()->getShippingAmount();  
                    
    ?>
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <ul class="forma_pagamento">
          <li style="float:left;;">
            <ul>
            	<li>
              		<img src="<?php echo $this->getSkinUrl('tray/checkoutredir/images/banner_semlogo_formas.png'); ?>" />
      			</li>
      
    	       <li>
	            <ul>
              	<li><label >Você será redirecionado para o Tray Checkout.</label></li>
            	</ul>
          	   </li>
        	</ul>
          </li>
    	</ul>
	</ul>
</fieldset>